---
name: Developer image

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push - dotnet${{ matrix.dotnet_major }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet_version: "7.0"
            dotnet_major: "7"
          - dotnet_version: "8.0"
            dotnet_major: "8"
          - dotnet_version: "10.0"
            dotnet_major: "10"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=raw,value=dev-dotnet${{ matrix.dotnet_major }}
            type=raw,value=dev,enable=${{ matrix.dotnet_major == '10' }}
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            DOTNET_VERSION=${{ matrix.dotnet_version }}
          tags: ${{ steps.meta.outputs.tags }}
